[package]
name = "avro-boxing"
description = "avro data formater convertors"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/davidkhala/rust-collection/"
license = "Apache-2.0"

[dependencies]
apache-avro = { version = "0.16.0"}
bigdecimal = { version = "0.4.5" }
