[package]
name = "avro-boxing"
description = "avro data format convertors"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/davidkhala/rust-collection/"
license = "Apache-2.0"

[dependencies]
apache-avro = "0.16.0"
bigdecimal = "0.4.5"
