on: push
jobs:
    moonrepo:
        runs-on: ubuntu-latest
        steps:
        - uses: moonrepo/setup-rust@v1
        # - run: cargo test
    actions-rust-lang:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        # - run: cargo test
    
    actions-rs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
        - uses: actions-rs/cargo@master
          with:
            command: check
    dtolnay:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        # - run: cargo test --all-features
