on: push
jobs:
    moonrepo:
        runs-on: ubuntu-latest
        steps:
        - uses: moonrepo/setup-rust@v1
        
    actions-rust-lang:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        
    
    actions-rs:
        # deprecated: out of maintain
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable

    dtolnay:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        
