on: push
jobs:
    moonrepo:
        runs-on: ubuntu-latest
        steps:
        - uses: moonrepo/setup-rust@v1
                
    actions-rust-lang:
        runs-on: ubuntu-latest
        steps:
        - uses: actions-rust-lang/setup-rust-toolchain@main
        
        
    
    actions-rs:
        # deprecated: out of maintain
        runs-on: ubuntu-latest
        steps:
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable

    dtolnay:
        runs-on: ubuntu-latest
        steps:
        - uses: dtolnay/rust-toolchain@master
          with:
              toolchain: stable
        - run: cargo login
