on: workflow_dispatch
jobs:
  avro-boxing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: avro-boxing
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-rs@main
      - run: cargo test
