on: push
jobs:
  ssl-windows:
    defaults:
      run:
        working-directory: ssl
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - uses: davidkhala/setup-rs@main
    - run: cargo check
      env:
        OPENSSL_DIR: C:\Program Files\OpenSSL
